// lib/pages/notes_page/constants/fake_constants.dart
import '../../../../models/Note.dart';
List<Note> notes = [
  Note(
    id: '14',
    title: 'GraphQL API Tasarımı',
    description: 'GraphQL ile ölçeklenebilir API geliştirme',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['GraphQL', 'API', 'Backend'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/graphql14/400/300',
    owner: 'Emre',
  ),
  Note(
    id: '15',
    title: 'Node.js Performance',
    description: 'Optimizing Node.js applications for speed',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Node.js', 'JavaScript', 'Backend'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/node15/400/300',
    owner: 'Fatma',
  ),
  Note(
    id: '16',
    title: 'Flutter Animasyonları',
    description: 'Flutter ile akıcı animasyonlar oluşturma',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Flutter', 'Animation', 'UI'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/flutter16/400/300',
    owner: 'Can',
  ),
  Note(
    id: '17',
    title: 'Cybersecurity Basics',
    description: 'Introduction to encryption and secure coding',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Cybersecurity', 'Security', 'Programming'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/security17/400/300',
    owner: 'Zeynep',
  ),
  Note(
    id: '18',
    title: 'MongoDB Veritabanı',
    description: 'NoSQL veritabanı tasarımı ve performans',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['MongoDB', 'NoSQL', 'Database'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/mongo18/400/300',
    owner: 'Hakan',
  ),
  Note(
    id: '19',
    title: 'React Native Essentials',
    description: 'Building cross-platform apps with React Native',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['React Native', 'Mobile', 'Frontend'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/reactnative19/400/300',
    owner: 'Selin',
  ),
  Note(
    id: '20',
    title: 'Kubernetes Temelleri',
    description: 'Konteyner orkestrasyonu ve dağıtım',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Kubernetes', 'DevOps', 'Cloud'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/k8s20/400/300',
    owner: 'Murat',
  ),
  Note(
    id: '21',
    title: 'Go Programming',
    description: 'Concurrent programming with Go',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Go', 'Backend', 'Concurrency'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/go21/400/300',
    owner: 'Ece',
  ),
  Note(
    id: '22',
    title: 'UI/UX Tasarım İlkeleri',
    description: 'Kullanıcı odaklı tasarım teknikleri',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['UI/UX', 'Design', 'Frontend'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/uiux22/400/300',
    owner: 'Berk',
  ),
  Note(
    id: '23',
    title: 'TensorFlow Basics',
    description: 'Deep learning with TensorFlow',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['TensorFlow', 'AI', 'ML'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/tensorflow23/400/300',
    owner: 'Deniz',
  ),
  Note(
    id: '24',
    title: 'Angular Geliştirme',
    description: 'Angular ile modern web uygulamaları',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Angular', 'JavaScript', 'Frontend'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/angular24/400/300',
    owner: 'Seda',
  ),
  Note(
    id: '25',
    title: 'CI/CD Pipelines',
    description: 'Automating deployments with Jenkins',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['CI/CD', 'DevOps', 'Automation'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/cicd25/400/300',
    owner: 'Tolga',
  ),
  Note(
    id: '26',
    title: 'Swift iOS Geliştirme',
    description: 'iOS uygulamaları için Swift programlama',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Swift', 'iOS', 'Mobile'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/swift26/400/300',
    owner: 'Elif',
  ),
  Note(
    id: '27',
    title: 'PostgreSQL Optimization',
    description: 'Advanced query optimization techniques',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['PostgreSQL', 'Database', 'Backend'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/postgres27/400/300',
    owner: 'Kaan',
  ),
  Note(
    id: '28',
    title: 'Siber Güvenlik Testleri',
    description: 'Penetrasyon testleri ve güvenlik açıkları',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Security', 'Penetration', 'Cybersecurity'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/cyber28/400/300',
    owner: 'Gizem',
  ),
  Note(
    id: '29',
    title: 'Vue.js Performance',
    description: 'Optimizing Vue.js applications',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Vue', 'JavaScript', 'Frontend'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/vue29/400/300',
    owner: 'Okan',
  ),
  Note(
    id: '30',
    title: 'Mikroservis Mimarisi',
    description: 'Dağıtık sistemlerde mikroservis tasarımı',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Microservices', 'Architecture', 'Backend'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/micro30/400/300',
    owner: 'Cem',
  ),
  Note(
    id: '31',
    title: 'Rust Programming',
    description: 'Safe and performant coding with Rust',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Rust', 'Programming', 'Systems'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/rust31/400/300',
    owner: 'Aslı',
  ),
  Note(
    id: '32',
    title: 'API Güvenliği',
    description: 'REST ve GraphQL API’lerde güvenlik önlemleri',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['API', 'Security', 'Backend'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/api32/400/300',
    owner: 'Barış',
  ),
  Note(
    id: '33',
    title: 'WebAssembly Guide',
    description: 'High-performance web applications with WebAssembly',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['WebAssembly', 'Web', 'Performance'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/wasm33/400/300',
    owner: 'Defne',
  ),
  Note(
    id: '34',
    title: 'Flutter State Yönetimi',
    description: 'Provider, Riverpod ve BLoC pattern',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Flutter', 'State', 'Mobile'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/flutter34/400/300',
    owner: 'Eren',
  ),
  Note(
    id: '35',
    title: 'Linux System Administration',
    description: 'Managing servers and automation with Linux',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Linux', 'SysAdmin', 'DevOps'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/linux35/400/300',
    owner: 'Merve',
  ),
  Note(
    id: '36',
    title: 'Redis Caching',
    description: 'Using Redis for high-performance caching',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Redis', 'Caching', 'Backend'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/redis36/400/300',
    owner: 'Onur',
  ),
  Note(
    id: '37',
    title: 'Svelte Framework',
    description: 'Building reactive apps with Svelte',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Svelte', 'Frontend', 'JavaScript'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/svelte37/400/300',
    owner: 'Irem',
  ),
  Note(
    id: '38',
    title: 'Big Data Analizi',
    description: 'Hadoop ve Spark ile büyük veri işleme',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Big Data', 'Hadoop', 'Spark'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/bigdata38/400/300',
    owner: 'Cihan',
  ),
  Note(
    id: '39',
    title: 'Unit Testing in Python',
    description: 'Writing effective unit tests with pytest',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Python', 'Testing', 'Backend'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/pytest39/400/300',
    owner: 'Aylin',
  ),
  Note(
    id: '40',
    title: 'Serverless Architecture',
    description: 'Building apps with AWS Lambda and serverless',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Serverless', 'AWS', 'Cloud'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/serverless40/400/300',
    owner: 'Umut',
  ),
  Note(
    id: '41',
    title: 'Agile Yazılım Geliştirme',
    description: 'Scrum ve Kanban metodolojileri',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Agile', 'Scrum', 'Project Management'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/agile41/400/300',
    owner: 'Yasin',
  ),
  Note(
    id: '42',
    title: 'Java Spring Boot',
    description: 'Building REST APIs with Spring Boot',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Java', 'Spring', 'Backend'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/spring42/400/300',
    owner: 'Derya',
  ),
  Note(
    id: '43',
    title: 'Oyun Geliştirme Unity',
    description: 'Unity ile 2D ve 3D oyun geliştirme',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Unity', 'GameDev', 'C#'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/unity43/400/300',
    owner: 'Fırat',
  ),
  Note(
    id: '44',
    title: 'Data Visualization',
    description: 'Creating interactive charts with D3.js',
    language: 'English',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['D3.js', 'DataViz', 'Frontend'],
    isPopular: false,
    imageUrl: 'https://picsum.photos/seed/d3js44/400/300',
    owner: 'Leyla',
  ),
  Note(
    id: '45',
    title: 'Elasticsearch Rehberi',
    description: 'Arama motoru optimizasyonu ve indeksleme',
    language: 'Türkçe',
    pdfPath:
    'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hashtags: ['Elasticsearch', 'Search', 'Backend'],
    isPopular: true,
    imageUrl: 'https://picsum.photos/seed/es45/400/300',
    owner: 'Kerem',
  ),
];