// Mocks generated by Mockito 5.4.6 from annotations
// in note_arkadasim/test/pages/add_note/add_note_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i11;
import 'dart:ui' as _i13;

import 'package:dio/dio.dart' as _i3;
import 'package:file_picker/src/file_picker.dart' as _i9;
import 'package:file_picker/src/file_picker_result.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:note_arkadasim/models/Note.dart' as _i7;
import 'package:note_arkadasim/models/note_add_model.dart' as _i8;
import 'package:note_arkadasim/models/note_upsert_data.dart' as _i2;
import 'package:note_arkadasim/providers/photo_provider.dart' as _i12;
import 'package:note_arkadasim/services/api_services/note_api/note_api_service.dart'
    as _i6;
import 'package:note_arkadasim/services/api_services/note_api/note_upsert_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNoteUpsertData_0 extends _i1.SmartFake
    implements _i2.NoteUpsertData {
  _FakeNoteUpsertData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoteUpsertService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteUpsertService extends _i1.Mock implements _i4.NoteUpsertService {
  MockNoteUpsertService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.NoteUpsertData> getNoteUpsertData() =>
      (super.noSuchMethod(
            Invocation.method(#getNoteUpsertData, []),
            returnValue: _i5.Future<_i2.NoteUpsertData>.value(
              _FakeNoteUpsertData_0(
                this,
                Invocation.method(#getNoteUpsertData, []),
              ),
            ),
          )
          as _i5.Future<_i2.NoteUpsertData>);

  @override
  _i5.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [NoteApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteApiService extends _i1.Mock implements _i6.NoteApiService {
  MockNoteApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get lastPageCount =>
      (super.noSuchMethod(Invocation.getter(#lastPageCount), returnValue: 0)
          as int);

  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_1(this, Invocation.getter(#dio)),
          )
          as _i3.Dio);

  @override
  set lastPageCount(int? value) => super.noSuchMethod(
    Invocation.setter(#lastPageCount, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i7.Note>> getNotesByPage() =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByPage, []),
            returnValue: _i5.Future<List<_i7.Note>>.value(<_i7.Note>[]),
          )
          as _i5.Future<List<_i7.Note>>);

  @override
  _i5.Future<bool> addNote(_i8.NoteAddModel? note) =>
      (super.noSuchMethod(
            Invocation.method(#addNote, [note]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void resetPagination() => super.noSuchMethod(
    Invocation.method(#resetPagination, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FilePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePicker extends _i1.Mock implements _i9.FilePicker {
  MockFilePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i10.FilePickerResult?> pickFiles({
    String? dialogTitle,
    String? initialDirectory,
    _i9.FileType? type = _i9.FileType.any,
    List<String>? allowedExtensions,
    dynamic Function(_i9.FilePickerStatus)? onFileLoading,
    bool? allowCompression = false,
    int? compressionQuality = 0,
    bool? allowMultiple = false,
    bool? withData = false,
    bool? withReadStream = false,
    bool? lockParentWindow = false,
    bool? readSequential = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickFiles, [], {
              #dialogTitle: dialogTitle,
              #initialDirectory: initialDirectory,
              #type: type,
              #allowedExtensions: allowedExtensions,
              #onFileLoading: onFileLoading,
              #allowCompression: allowCompression,
              #compressionQuality: compressionQuality,
              #allowMultiple: allowMultiple,
              #withData: withData,
              #withReadStream: withReadStream,
              #lockParentWindow: lockParentWindow,
              #readSequential: readSequential,
            }),
            returnValue: _i5.Future<_i10.FilePickerResult?>.value(),
          )
          as _i5.Future<_i10.FilePickerResult?>);

  @override
  _i5.Future<List<String>?> pickFileAndDirectoryPaths({
    String? initialDirectory,
    _i9.FileType? type = _i9.FileType.any,
    List<String>? allowedExtensions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickFileAndDirectoryPaths, [], {
              #initialDirectory: initialDirectory,
              #type: type,
              #allowedExtensions: allowedExtensions,
            }),
            returnValue: _i5.Future<List<String>?>.value(),
          )
          as _i5.Future<List<String>?>);

  @override
  _i5.Future<bool?> clearTemporaryFiles() =>
      (super.noSuchMethod(
            Invocation.method(#clearTemporaryFiles, []),
            returnValue: _i5.Future<bool?>.value(),
          )
          as _i5.Future<bool?>);

  @override
  _i5.Future<String?> getDirectoryPath({
    String? dialogTitle,
    bool? lockParentWindow = false,
    String? initialDirectory,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDirectoryPath, [], {
              #dialogTitle: dialogTitle,
              #lockParentWindow: lockParentWindow,
              #initialDirectory: initialDirectory,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> saveFile({
    String? dialogTitle,
    String? fileName,
    String? initialDirectory,
    _i9.FileType? type = _i9.FileType.any,
    List<String>? allowedExtensions,
    _i11.Uint8List? bytes,
    bool? lockParentWindow = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFile, [], {
              #dialogTitle: dialogTitle,
              #fileName: fileName,
              #initialDirectory: initialDirectory,
              #type: type,
              #allowedExtensions: allowedExtensions,
              #bytes: bytes,
              #lockParentWindow: lockParentWindow,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);
}

/// A class which mocks [PhotoProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoProvider extends _i1.Mock implements _i12.PhotoProvider {
  MockPhotoProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setPhoto(String? path) => super.noSuchMethod(
    Invocation.method(#setPhoto, [path]),
    returnValueForMissingStub: null,
  );

  @override
  void clearPhoto() => super.noSuchMethod(
    Invocation.method(#clearPhoto, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
